[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--import tsx"
PORT = "3000"

[start]
cmd = "npm start"
